# -----------------------------------------------------
# |             Companion - by Alps BTE
# -----------------------------------------------------
# | [Github Repo] https://github.com/AlpsBTE/Companion
# | [Contacts - Discord] R3tuxn#7169
# -----------------------------------------------------

# IP and Port to the HUB server
hub:
  IP: localhost
  port: 0000


# -----------------------------------------------------
# | Spawn points to specific locations on the TERRA sever
# -----------------------------------------------------
spawn-points:
  # The map is used as spawn for the TERRA server
  map:
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
  # The trees platform is used to copy trees and bushes for building
  trees:
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0


# -----------------------------------------------------
# | Formatting: Info/Error message outputs
# -----------------------------------------------------
message-prefix: §7§l>>
info-colour: §a
error-colour: §c


# NOTE: Do not change
config-version: 1.0