main: com.alpsbte.companion.Companion
version: 2.0
api-version: 1.12.2
name: AlpsBTE-Companion
author: R3tuxn
softdepend: [HeadDatabase]

commands:
  setspawn:
    description: Set spawn point of the map or tree platform
    usage: /setspawn <map/trees>
  creload:
    description: Reload companion config
    usage: /creload
  map:
    description: Teleport to the spawn map
    usage: /map
  speed:
    description: Adjust your flying speed
    usage: /speed <1/2/3>
  hub:
    description: Connect to the HUB server
    usage: /hub
  companion:
    description: Open the companion menu
    usage: /companion
  tpp:
    description: Teleport to a player
    usage: /tpp <Player>
  ptime:
    description: Set player time which is not relative to the server
    usage: /ptime <day/night/reset/ticks>
  pweather:
    description: Set player weather which is not relative to the server
    usage: /pweather <rain/clear/reset>