main: github.BTECompanion.BTECompanion
version: 2.0
api-version: 1.12.2
name: AlpsBTE-Companion
author: R3tuxn
depend: [HeadDatabase]

commands:
  setspawnpoint:
    description: set spawn point of the map or tree platform
    usage: /setspawn <map/trees>
    permission: companion.setspawn
  creload:
    description: reload companion config
    usage: /creload
    permission: companion.creload
  map:
    description: teleport to the countries map
    usage: /map
    permission: companion.map
  speed:
    description: adjust your flying speed
    usage: /speed <1/2/3>
    permission: companion.speed
  hub:
    description: connect to the HUB server
    usage: /hub
    permission: companion.hub
  companion:
    description: open the companion menu
    usage: /companion
    permission: companion.companion
  tpp:
    description: teleport to a player
    usage: /tpp <Player>
    permission: companion.tpp
  createplot:
    description: create a new plot for the PlotSystem
    usage: /createplot
    permission: companion.createplot
  pasteplot:
    description: paste a plot
    usage: /pasteplot <ID>
    permission: companion.plot